### ISSUE TITLE
Single batch: Supervised or Unsupervised

### ISSUE THREAD

**Issue by AKASH2907** [soo89/CSD-SSD#12]
hi, 
in the experiment section, you mentioned that labeled and unlabeled data are randomly shuffled and selected. I wanted to know why it's necessary to have each mini-batch containing both labeled as well as unlabeled data?

What happens if one of mini-batch contains only unlabeled data (since the majority of data is unlabeled)? Can we handle that case? What would be the value of loss? 

I'm new to semi-supervised. 
thanks.

**Comment by soo89** [comment]
In semi-supervised learning of classification, the minibatch size is very large (100-512). Therefore, labeled and unlabeled losses can be calculated simultaneously within one mini-batch. In the same way as above, we want labeled data and unlabeled data to be calculated simultaneously.

In the case of SSD, since the mini-batch size is large(32), we followed the same as the classification. In the case of R-FCN, however, since the mini-batch size is 4, we sampled labeled and unlabeled data as 1:3.
