### ISSUE TITLE
Training on GPUs

### ISSUE THREAD

**Issue by ZhuoranYu** [soo89/CSD-SSD#7]
Hello,

Thanks for your nice work. I just have few questions about training on GPUs. 

1. Do you train your CSD on a single GPU or multiple GPUs? If trained on single GPU, do you mind sharing the series code(what type of GPU)? I am asking this because I am not able to train CSD with batch size of 32 on a single 2080 Ti and I'm not sure whether the problem is on my server or the nature of the code.

2. What's your estimated training time on VOC(07 labeled and 12 unlabeled) in your configuration? It looks like training a baseline SSD on a single GPU would take me several days in my case so it would be nice if you could share the stats....

Thanks for your time and enjoy your day!

**Comment by soo89** [comment]
Thanks for your interest in our research.

1. We used Nvidia 1080Ti GPU, and we assigned 4 and 8 GPUs for SSD300 and SSD512 models with CSD training, respectively.

SSD300 model with CSD is required about 17GB of GPU memory.
(SSD300 with CSD can be trained with 2 GPUs.)

-  With fewer GPUs, it can be difficult to train because of a limited memory budget.

2. When training the SSD300 + CSD model with 4 GPUs, it takes about 1 day.

Thank you.
